In [1]:
# import modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
# read file
dataset = pd.read_csv("Buy_Book.csv")
x = dataset.iloc[:,[0]].values
    
dataset['Buy Book'] = dataset['Buy Book'].replace('Yes',1)
dataset['Buy Book'] = dataset['Buy Book'].replace('No',0)
    
y = dataset.iloc[:,[4]].values

In [21]:
#split the data into training and testing data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
x_train,x_test,y_train,y_test

(array([[32],
        [42],
        [31],
        [49],
        [28],
        [34],
        [45],
        [43],
        [49],
        [24],
        [35],
        [44],
        [32],
        [41],
        [25],
        [27],
        [43],
        [36],
        [27],
        [21]], dtype=int64), array([[42],
        [39],
        [38],
        [46],
        [34]], dtype=int64), array([[1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1]], dtype=int64), array([[0],
        [1],
        [1],
        [0],
        [1]], dtype=int64))

In [22]:
# train the model
logi_reg = LogisticRegression()
logi_reg.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
# predict the values
y_pred = logi_reg.predict(x_test)   
y_pred

array([1, 1, 1, 1, 1], dtype=int64)

In [24]:
# accuracy of the model 
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.6

In [25]:
# confusion matrix, acuuracy is less bcz we included all the variales and Collinearity increases.
cm = confusion_matrix(y_test,y_pred)
cm

array([[0, 2],
       [0, 3]], dtype=int64)